[package]
name = "localization"
version = "0.1.0"
edition.workspace = true
description = "Localization utilities for Zed UI"
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
parking_lot.workspace = true
gpui.workspace = true
settings.workspace = true
